
package com.bush76.core.ws.client.hello;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHelloService", targetNamespace = "http://server.ws.core.bush76.com/")
public interface IHelloService {

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.SayResponse")
    public String say(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @return
     *     returns java.util.List<com.bush76.core.ws.client.hello.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.ListResponse")
    public List<User> list();

    /**
     * 
     * @return
     *     returns com.bush76.core.ws.client.hello.MapConvertor
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserMap", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.GetUserMap")
    @ResponseWrapper(localName = "getUserMapResponse", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.GetUserMapResponse")
    public MapConvertor getUserMap();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.GetUserResponse")
    public String getUser();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveUser", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.SaveUser")
    @ResponseWrapper(localName = "saveUserResponse", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.SaveUserResponse")
    public String saveUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @return
     *     returns com.bush76.core.ws.client.hello.MapConvertor
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMapObject", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.GetMapObject")
    @ResponseWrapper(localName = "getMapObjectResponse", targetNamespace = "http://server.ws.core.bush76.com/", className = "com.bush76.core.ws.client.hello.GetMapObjectResponse")
    public MapConvertor getMapObject();

}
